### ISSUE TITLE
Not full output, 404 error and array error

### ISSUE THREAD

**Issue by ievarau** [wassermanlab/gene2wordclouds#5]
Hi, Oriol,

I noticed that I often get HTTP error on the first try of running the wordclouds script. It is enough to re-run the command and then everything works. This is slightly unsustainable. I can get around this for now, but I was wondering, if it would be possible to look into this and make it a bit more stable.

```
 File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 
```

Best,
Ieva

**Comment by ievarau** [comment]
Ok, this is starting to become a bigger issue. We are trying to run this on new data now, but besides 404 error we get a "reshape" error:

I have also came across another error that I suspect happens, because some values are not found.

```
Traceback (most recent call last):
  File "/storage/mathelierarea/processed/ieva/projects/JASPAR_2024/jaspar_2024_downstream/new_structure/jaspardownstream/external_tools/wordclouds/tools/gene2wordclouds/gene2wordclouds.py", line 584, in <module>
    main()
  File "/div/pythagoras/u2/ievarau/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/div/pythagoras/u2/ievarau/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/div/pythagoras/u2/ievarau/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/div/pythagoras/u2/ievarau/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/storage/mathelierarea/processed/ieva/projects/JASPAR_2024/jaspar_2024_downstream/new_structure/jaspardownstream/external_tools/wordclouds/tools/gene2wordclouds/gene2wordclouds.py", line 140, in main
    __get_gene2comparison(filt_entrezids, gene_info, stem_aliases, out_dir)
  File "/storage/mathelierarea/processed/ieva/projects/JASPAR_2024/jaspar_2024_downstream/new_structure/jaspardownstream/external_tools/wordclouds/tools/gene2wordclouds/gene2wordclouds.py", line 581, in __get_gene2comparison
    __get_pairwisecomparison(stems_df, entrezids, tfclass, gene_info, entrezids2stems, 2, tfidfs_dir, stats_dir)
  File "/storage/mathelierarea/processed/ieva/projects/JASPAR_2024/jaspar_2024_downstream/new_structure/jaspardownstream/external_tools/wordclouds/tools/gene2wordclouds/utils/gene2genecomparison.py", line 187, in __get_pairwisecomparison
    __get_abspres_cosine_class(order_entrezids, colors, abspres_vec, legend, patch, outdir)
  File "/storage/mathelierarea/processed/ieva/projects/JASPAR_2024/jaspar_2024_downstream/new_structure/jaspardownstream/external_tools/wordclouds/tools/gene2wordclouds/utils/gene2genecomparison.py", line 275, in __get_abspres_cosine_class
    matrix = cosine_similarity(vectors)
  File "/div/pythagoras/u2/ievarau/.conda/envs/wordclouds/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 1180, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "/div/pythagoras/u2/ievarau/.conda/envs/wordclouds/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/div/pythagoras/u2/ievarau/.conda/envs/wordclouds/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 142, in check_pairwise_arrays
    X = Y = check_array(X, accept_sparse=accept_sparse, dtype=dtype,
  File "/div/pythagoras/u2/ievarau/.conda/envs/wordclouds/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/div/pythagoras/u2/ievarau/.conda/envs/wordclouds/lib/python3.8/site-packages/sklearn/utils/validation.py", line 637, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

But **more importantly, only 25 wordclouds are produced** for any list of UniProt IDs, which is quite strange.

We suspect that it might be `gene_info.gz` file download that causes 404 problem or something related to missing info for different UniProt IDs. Why `gene_info.gz` is downloaded, while `gene2pubmed.gz` is stored in the repo? Are all `utils/data` files universal to any kind of input or they should also be fetched from databases like `gene_info.gz` ? I am wondering, if the workflow detects them as existing and then they are not updated. Such files could always be downloaded in the output directory and not `utils/data` (this actually messes up within the container, since it is `read-only` system). Just to note that these errors occur also when running from the conda environment as instructed.

It would be great, if you could help us with this.

Best,
Ieva

P.S. I am attaching a short list of uniprot IDs that produces the errors.

[test_list_of_uniprot_ids.txt](https://github.com/wassermanlab/gene2wordclouds/files/11904279/test_list_of_uniprot_ids.txt)
